language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4]

env:
  global:
    - NODE_VERSION=''
    - ZOMBIE_VERSION=''
    # Force binding to IPv4 as Zombie and PHP seem to have a different resolution for localhost on Travis.
    - MINK_HOST=127.0.0.1:8002

matrix:
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.3
      dist: precise
      env:
        - MINK_PHP_BIN=~/.phpenv/versions/5.6/bin/php
        - NODE_VERSION='8.12.0'
    - php: 5.6
      env:
        - NODE_VERSION='5.4.1'
        - ZOMBIE_VERSION='@^4.0'
    - php: 5.6
      env:
        - NODE_VERSION='6.17.1'
        - ZOMBIE_VERSION='@^5.0'

before_install:
  - if [[ "$NODE_VERSION" != "" ]]; then wget https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz && tar xf node-v${NODE_VERSION}-linux-x64.tar.xz && export PATH="`pwd`/node-v${NODE_VERSION}-linux-x64/bin:$PATH"; fi

  - node --version
  - npm --version

install:
  - composer install
  - npm install zombie$ZOMBIE_VERSION

before_script:
   # Start a webserver for web fixtures.
  - vendor/bin/mink-test-server > /dev/null 2>&1 &

script: vendor/bin/phpunit -v --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
